################################################################################
mission_director:
  ros__parameters:
    frequency: 10.0 # [Hz]
    sils_mode: '1' # 0: Normal, 1: SILS
    maneuver_mode: '1' # 1: Free running, 2: Docking, 3: DP, 4: Navigation
      # 1: Free running
        # 0: Speed mapping, 1: Turning, 2: Zigzag, 3: Pivot turn, 4: Crabbing, 5: Pull out, 6: Spiral, 7: Bangbang, 8: 3321
      # 2: Docking
        # 0: Heuristic (Entering), 1: Deep-RL (Entering), 2: Heuristic (Multi-stage), 3 : Deep-RL (Multi-stage)
      # 3: DP
        # TBD
      # 4: Navigation
        # TBD
    sub_maneuver_mode: '7'
      # 0: Speed mapping, 1: Turning, 2: Zigzag, 3: Pivot turn, 4: Crabbing, 5: Pull out, 6: Spiral, 7: Bangbang, 8: 3321
    subsub_maneuver_mode: '0' 
      # 2: Docking
        # 0: Approaching stage, 1: Turning stage, 2: Entering stage, 3: Pushing stage
    sensor_mode: '1' # 0: Qualisys, 1: SLAM, 2: GPS-RTK, 3: Marker, 4: SILS
    motor_mode: '0' # 0: Manual, 1: Auto
    status: '0' # Initializing, 1: Running, 2: Stop, 3: Standby, 4: Complete
################################################################################
controller:
  ros__parameters:
    common_params:
      del_rate: 100.0 # [deg/s]
      rps_rate: 60.0 
      rps_max: 30.0 # [rad/s]
      del_max: 35.0 # [deg]
      deadzone_start: 1 # rps
      deadzone_end:   1 # rps
      frequency: 10.0 # [Hz]

    free_running_mode : 
      speed_mapping_mode:
        len_timeseries: 100
        target_rps : 0.0
        target_del : 0.0
        conv_u_tol : 0.05 # [m/s]
        duration : 0.0 # [s]

      turning_mode:
        target_rps : 30.0
        target_del : 30.0
        duration : 1000.0 # [s]

      zigzag_mode:
        target_rps : 20.0
        target_psi : 10.0
        initial_psi_direction : 1 # 1: Right, -1: Left
        duration : 300.0 # [s]

      pivot_turn_mode:
        target_rpsP : 0.0
        target_rpsS : 0.0
        duration : 0.0 # [s]

      crabbing_mode:
        target_rpsP : 0.0
        target_rpsS : 0.0
        target_delP : 0.0
        target_delS : 0.0
        duration : 0.0 # [s]

      pull_out_mode:
        target_rps : 20.0
        target_del : 20.0
        duration_turning : 10.0 # [s]
        duration_neutral : 10.0 # [s]

      spiral_mode:
        target_rps : 20.0
        target_del : [20.0, 10.0, 5.0]
        duration : 20.0 # [s]

      bangbang_mode:
        target_rps : 20.0
        target_del : 20.0
        initial_psi_direction : 1 # 1: Right, -1: Left
        duration : 5.0 # [s]
        repeat: 4

      3321_mode:
        target_rps : 20.0
        target_del : 20.0
        initial_psi_direction : 1 # 1: Right, -1: Left
        duration : 5.0 # [s]
        repeat: 4
##################################################################################
